<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 21,
                'name' => 'Francis',
                'slug' => 'francis-amuche',
                'last_name' => 'Amuche',
                'email' => 'f.amuche@gmail.com',
                'email_verified_at' => '2021-08-24 07:33:19',
                'password' => '$2y$10$ekH.DDo2armNzJ4qY8tBEuMATJotTjuz/W3PhsD6hzu9t9GsU6dTO',
                'company' => NULL,
                'avatar' => 'https://i.ibb.co/1rnQzbx/young-man-with-eyeglasses.jpg',
                'address' => '3 Babatunde Jose street victoria Island, Lagos, Nigeria',
                'phone' => '09054675433',
                'job_title' => 'Treasurer',
                'hire_date' => '2021-03-21',
                'date_of_birth' => '1976-08-13',
                'employee_status' => 'Full-time',
                'department_id' => 1,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => 'App\\Models\\Admin',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-03-21 04:27:53',
                'updated_at' => '2021-03-21 04:27:53',
            ),
            1 => 
            array (
                'id' => 22,
                'name' => 'Danny',
                'slug' => 'danny-schuster',
                'last_name' => 'Schuster',
                'email' => 'DannieS@example.net',
                'email_verified_at' => NULL,
                'password' => '$2y$10$G6BlaedOKXUTKA2d1bvvbehS3PkgLr1NHM5jzmf8uqoOiVltrQIK6',
                'company' => NULL,
                'avatar' => 'https://i.ibb.co/S36z2kw/3.jpg',
                'address' => '39B Freedom Way, ikate 100001, Lagos',
                'phone' => '08065775433',
                'job_title' => 'System Administrator',
                'hire_date' => '2017-01-04',
                'date_of_birth' => '1985-07-03',
                'employee_status' => 'Full-time',
                'department_id' => 2,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-01-30 05:11:29',
                'updated_at' => '2021-01-30 05:11:29',
            ),
            2 => 
            array (
                'id' => 23,
                'name' => 'Kehinde',
                'slug' => 'kehinde-abayomi',
                'last_name' => 'Abayomi',
                'email' => 'kenny4all40@gmail.com',
                'email_verified_at' => '2021-08-24 11:52:20',
                'password' => '$2y$10$i.9M8JtXj51TkLfNdK2Kw.f53.wHovvBZHkRDmMuI3B61e7Q2iIUK',
                'company' => NULL,
                'avatar' => 'https://i.ibb.co/FmdbwFb/4.jpg',
                'address' => '26 Isaac John St, Onigbongbo 100271, Lagos',
                'phone' => '08184675490',
                'job_title' => 'Account Executive',
                'hire_date' => '2019-06-01',
                'date_of_birth' => '1990-01-17',
                'employee_status' => 'Full-time',
                'department_id' => 3,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-01-30 05:20:31',
                'updated_at' => '2021-01-30 05:25:01',
            ),
            3 => 
            array (
                'id' => 25,
                'name' => 'Paul',
                'slug' => 'paul-smith',
                'last_name' => 'Smith',
                'email' => 'psmith@si.com',
                'email_verified_at' => '2021-08-24 11:52:47',
                'password' => '$2y$10$yOcwb7FWcWWzO.H/S.IpCOCYCzfM1P7OyQrY4u52ydevusLI4QkRK',
                'company' => NULL,
                'avatar' => 'https://i.ibb.co/WxYYy5w/6.jpg',
                'address' => '165 Herbert Macaulay Way, Adekunle 101245, Lagos',
                'phone' => '08070890987',
                'job_title' => 'Treasurer',
                'hire_date' => '2021-03-21',
                'date_of_birth' => '1976-08-13',
                'employee_status' => 'Full-time',
                'department_id' => 1,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-01-30 05:47:47',
                'updated_at' => '2021-01-30 05:47:47',
            ),
            4 => 
            array (
                'id' => 27,
                'name' => 'Eke',
                'slug' => 'eke-uka',
                'last_name' => 'Uka',
                'email' => 'papa28x4@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$e8uwxuo8DM7JqDT0r1MTd.b3r4U/FuQD4.2lyFCQ3naTA8Qu3hR.6',
                'company' => NULL,
                'avatar' => 'https://i.ibb.co/SQhcfYJ/1.jpg',
                'address' => 'No 1, Ohafia Street, Ago Place Way, Okota, Lagos',
                'phone' => '08170464445',
                'job_title' => 'EDMS Support',
                'hire_date' => '2020-01-11',
                'date_of_birth' => '1995-11-22',
                'employee_status' => 'Contract',
                'department_id' => 4,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => 'App\\Models\\Admin',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-01-30 05:51:24',
                'updated_at' => '2021-01-30 05:52:43',
            ),
            5 => 
            array (
                'id' => 29,
                'name' => 'Felicia',
                'slug' => 'felicia-carlos',
                'last_name' => 'Carlos',
                'email' => 'feliciacarlos@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$apkz1GXDEQA3CaAFAj./fu8kreIZL1JkRFbNU/p95MFSDl0FOzTJ.',
                'company' => NULL,
                'avatar' => 'https://i.ibb.co/HXFsgCX/8.jpg',
                'address' => 'Plot 1232, Bishop Oluwole Street, Victoria Island, Lagos',
                'phone' => '08126770089',
                'job_title' => 'Business Development Executive',
                'hire_date' => '2020-09-11',
                'date_of_birth' => '1980-10-16',
                'employee_status' => 'Full-time',
                'department_id' => 5,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-01-30 06:40:51',
                'updated_at' => '2021-01-30 06:40:51',
            ),
            6 => 
            array (
                'id' => 30,
                'name' => 'Rake',
                'slug' => 'rake-bake',
                'last_name' => 'Bake',
                'email' => 'rake@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZPFaOK.e9zaJIIWmeQVG5uLZsx7KMcizymANzWrGuKSyGLiWa8zWW',
                'company' => 'JBLy',
                'avatar' => 'user/avatar/1643040575-face3.jpg',
                'address' => 'Plot 2, Oyeleke Street, Oregun, Alausa, Ikeja',
                'phone' => '08070938765',
                'job_title' => 'Inspector',
                'hire_date' => '2021-02-09',
                'date_of_birth' => '1988-02-23',
                'employee_status' => 'Full-time',
                'department_id' => 6,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => 'App\\Models\\Admin',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-02-27 11:23:48',
                'updated_at' => '2022-01-24 16:09:36',
            ),
            7 => 
            array (
                'id' => 31,
                'name' => 'Mark',
                'slug' => 'mark-paul',
                'last_name' => 'Paul',
                'email' => 'markus@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$RYNiqXnMdAdVkb4Rz9nuoecyN18fh0ca1fvxwrR33aSndFAFwTq3K',
                'company' => NULL,
                'avatar' => 'user/avatar/1643040873-face7.jpg',
                'address' => 'Plot 161A, Idejo Street, Victoria Island, Lagos',
                'phone' => '08060885432',
                'job_title' => 'Intern',
                'hire_date' => '2022-01-04',
                'date_of_birth' => '2001-12-12',
                'employee_status' => 'Intern',
                'department_id' => 7,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-03-01 12:11:09',
                'updated_at' => '2022-01-24 16:14:55',
            ),
            8 => 
            array (
                'id' => 37,
                'name' => 'Anna',
                'slug' => 'anna-smith',
                'last_name' => 'Smith',
                'email' => 'annasmith@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/.o8GPqxqBah4EYnbk9EY.R4zX1QH.9znoyyOINw69/9qRh6iDBbu',
                'company' => NULL,
                'avatar' => NULL,
                'address' => '12 Saka Tinubu St, Adeola Odeku Street, IRU, Victoria Island, Lagos',
                'phone' => '08050675808',
                'job_title' => 'HRM',
                'hire_date' => '2018-04-01',
                'date_of_birth' => '1968-02-07',
                'employee_status' => 'Full-time',
                'department_id' => 9,
                'country' => 'Nigeria',
                'terms' => 0,
                'active' => 1,
                'type' => 'App\\Models\\Admin',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-06-26 07:00:13',
                'updated_at' => '2021-07-07 17:04:29',
            ),
            9 => 
            array (
                'id' => 39,
                'name' => 'Raheem',
                'slug' => 'raheem-sterling',
                'last_name' => 'Sterling',
                'email' => 'divingking@example.com',
                'email_verified_at' => '2021-07-12 08:08:32',
                'password' => '$2y$10$FsLyRGnrLzGOCi8YYPL6d.1SkruOmvCr7xIyKXIKSfdRpbPT8TSe.',
                'company' => NULL,
                'avatar' => NULL,
                'address' => '5 Moronfolu St, Akoka 100001, Lagos',
                'phone' => '08014600493',
                'job_title' => 'Senior Service Engineer',
                'hire_date' => '2015-08-31',
                'date_of_birth' => '1976-08-13',
                'employee_status' => 'Full-time',
                'department_id' => 7,
                'country' => 'Nigeria',
                'terms' => 0,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-07-12 08:06:25',
                'updated_at' => '2021-07-12 08:08:32',
            ),
            10 => 
            array (
                'id' => 41,
                'name' => 'Jada',
                'slug' => 'jada-sancho',
                'last_name' => 'Sancho',
                'email' => 'jshow@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$4AGg3SE1yKMcPrFqHj7YFOkcsoJhqqtrMc5mI03NCC53s5n9Dqula',
                'company' => NULL,
                'avatar' => NULL,
                'address' => '13 Obalende, Breadfruit St, Lagos',
                'phone' => '08022368008',
                'job_title' => 'Service Engineer',
                'hire_date' => '2021-06-21',
                'date_of_birth' => '1991-07-13',
                'employee_status' => 'Full-time',
                'department_id' => 7,
                'country' => 'Nigeria',
                'terms' => 0,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-07-12 08:18:13',
                'updated_at' => '2021-07-12 08:18:13',
            ),
            11 => 
            array (
                'id' => 42,
                'name' => 'Pope',
                'slug' => 'pope-nick',
                'last_name' => 'Nick',
                'email' => 'nickpope@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7A4vIvL3TEdiONMT8pgzu.ioAsr0wlo/Q3fJNSyVVxoR10OvKfX26',
                'company' => NULL,
                'avatar' => 'user/avatar/1643031305-face13.jpg',
                'address' => 'Plot 927/928, Bishop Aboyade Cole Street Victoria Island',
                'phone' => '08054678403',
                'job_title' => 'Service Engineer',
                'hire_date' => '2021-06-21',
                'date_of_birth' => '1976-08-13',
                'employee_status' => 'Full-time',
                'department_id' => 7,
                'country' => 'Nigeria',
                'terms' => 0,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-07-12 08:24:54',
                'updated_at' => '2022-01-24 13:35:27',
            ),
            12 => 
            array (
                'id' => 43,
                'name' => 'Mia',
                'slug' => 'mia-chang',
                'last_name' => 'Chang',
                'email' => 'miachang@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$aj3dldb.6JNBH5JXvyPMOO1SWGFpAH3ytO6nQu4yGMCnLO/YuqXMG',
                'company' => NULL,
                'avatar' => 'user/avatar/1643031085-face6.jpg',
                'address' => 'NO. 11, BEN OKAGBUE STREET, LEKKI PHASE 1, LAGOS',
                'phone' => '08013445433',
                'job_title' => 'Logistics Manager',
                'hire_date' => '2019-02-02',
                'date_of_birth' => '1976-08-13',
                'employee_status' => 'Intern',
                'department_id' => 8,
                'country' => 'Nigeria',
                'terms' => 0,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-07-12 09:46:36',
                'updated_at' => '2022-01-24 13:31:49',
            ),
            13 => 
            array (
                'id' => 44,
                'name' => 'Super',
                'slug' => 'super-admin',
                'last_name' => 'Admin',
                'email' => 'admin@example.com',
                'email_verified_at' => '2021-08-24 07:33:19',
                'password' => '$2y$10$ekH.DDo2armNzJ4qY8tBEuMATJotTjuz/W3PhsD6hzu9t9GsU6dTO',
                'company' => NULL,
                'avatar' => NULL,
                'address' => NULL,
                'phone' => '09054675433',
                'job_title' => NULL,
                'hire_date' => NULL,
                'date_of_birth' => NULL,
                'employee_status' => NULL,
                'department_id' => NULL,
                'country' => 'Nigeria',
                'terms' => 1,
                'active' => 1,
                'type' => 'App\\Models\\Admin',
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2021-03-21 04:27:53',
                'updated_at' => '2021-03-21 04:27:53',
            ),
            14 => 
            array (
                'id' => 45,
                'name' => 'Young',
                'slug' => 'young-ashley',
                'last_name' => 'Ashley',
                'email' => 'blm@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$qOBtF3fPyEjBaCTOp8cFIOhv6Pgldv2miAU/sptd.vJ.Zz3wCQ7ra',
                'company' => NULL,
                'avatar' => 'user/avatar/1643034794-face15.jpg',
                'address' => NULL,
                'phone' => '08090456899',
                'job_title' => NULL,
                'hire_date' => NULL,
                'date_of_birth' => NULL,
                'employee_status' => NULL,
                'department_id' => NULL,
                'country' => NULL,
                'terms' => 0,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2022-01-24 14:33:37',
                'updated_at' => '2022-01-24 14:33:37',
            ),
            15 => 
            array (
                'id' => 46,
                'name' => 'Faith',
                'slug' => 'faith-rooney',
                'last_name' => 'Rooney',
                'email' => 'frooney@example.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$8Uk03NvfUE5qrN.kv//lW.V1mchkgm3CfZuseSo4iI2Vc.ugpd00S',
                'company' => NULL,
                'avatar' => 'user/avatar/1643041441-avatar-2.jpg',
                'address' => '21 Lugard Road. Ikoyi. Lagos',
                'phone' => '08096776554',
                'job_title' => 'Intern',
                'hire_date' => '2022-01-03',
                'date_of_birth' => '2001-02-24',
                'employee_status' => 'Intern',
                'department_id' => 6,
                'country' => NULL,
                'terms' => 0,
                'active' => 1,
                'type' => NULL,
                'remember_token' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2022-01-24 16:22:56',
                'updated_at' => '2022-01-24 16:24:02',
            ),
        ));
        
        
    }
}